### ISSUE TITLE
Update to Julia 0.7 / 1.0

### ISSUE THREAD

**Issue by Datseris** [JuliaDynamics/DynamicalBilliards.jl#107]
- [x] Unrolled.jl does not work on 0.7 and I don't know whether we can count on them to update in time. We should simply benchmark whether we actually need it. I don't think we do any more, because accessing a tuple field is now the same as accessing the tuple itself.
- [x] Use `sincos` everywhere.
- [x] Remove all deprecation warnings. 
- [x] Constantly run package benchmarks to detect regressions.
- [x] Make sure tests pass locally.
- [x] Make sure tests pass on Travis/Appveyor.
- [x] Document any API changes *if* they occur (I don't think so).

**Comment by lhupe** [comment]
I ran tests and noted down everything that still needs to be changed
* Change `Array{T, 1}(42)` to `Array{T, 1}(undef, 42)` to create uninitialised arrays (poincaresos.jl, line 30)
* Change `A[someInterval...] = x` to `A[someInterval...] .= x ` to broadcast the assignment (raysplitting.jl, line 74)
* add `using LinearAlgebra` to runtests.jl and MushroomTools
* add `using Dates` to runtests.jl
* change all references to `Base.Test` (which has been moved to the stdlib module `Test`)
* add the `digits` kwarg to all `round` calls in the test files
* add a version number to Project.toml
* sometimes, we get this warning: `WARNING: Base.uninitialized is deprecated, use undef instead.
`. I think it's something to do with how we initialise StaticArrays, because it is always preceded by `WARNING: importing deprecated binding Base.uninitialized into StaticArrays.`. Maybe the problem is in StaticArrays,
* I have prematurely changed the `qr` call in lyapunov_spectrum.jl to match the new convention (i. e. a `LinearAlgebra.QR` object is returned), but the StaticArrays ` qr` function hasn't been  changed yet. We'll either have to revert my change or open an issue with StaticArrays

**Comment by lhupe** [comment]
Aaaand there's another thing: Precompiling throws a warning which I don't entirely understand
```
WARNING: Method definition __init__() in module Requires at /home/lukas/.julia/packages/Requires/bNVE/src/init.jl:9 overwritten in module DynamicalBilliards at /home/lukas/.julia/packages/Requires/bNVE/src/init.jl:9.
```

**Comment by Datseris** [comment]
No API changes and we don't need Unrolled anymore. Using good ol' metaprogramming did the job.
