### ISSUE TITLE
Documentation and newest release not synchronized...

### ISSUE THREAD

**Issue by Sleort** [JuliaDynamics/DynamicalBilliards.jl#42]
I noticed that the most current release of DynamicalBilliards is version 1.5.1, while the documentation seems to be geared towards v1.6.  In case this is intended: Maybe it would be nice to keep two versions of the documentation, like latest/stable? (In that way the reputation of a nice package doesn't get tarnished by failing examples in the documentation :wink:  )

**Comment by Datseris** [comment]
Hello @Sleort .
There are already two versions of the documentation, here is the stable one: https://juliadynamics.github.io/DynamicalBilliards.jl/stable/

I will include a link for the "stable" documentation in the next release, so that does not happen again :D 

Thank you very much for you kind words though! I am curious, but are you using the package for research?

**Comment by Sleort** [comment]
Oh, I see. Great! (And thanks for the prompt response!)

Only some hobby "research" (for the moment). I'm basically trying to simulate some random particle scattering (think of a simplified Rutherford gold foil experiment). So maybe not the main purpose of DynamicalBilliards... :smile:
